# Site settings
title: MMP240
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the class note for Multimedia Development class, an intro-level Web Development class offered by City University of New York.
baseurl: "/MMP240"
#baseurl: ""
url: "/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown


excerpt_separator: "" # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
